server:
  port: 7070

spring:
  application:
    name: MOVIE-SERVICE
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/movie
    username: movie_user
    password: movie_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect